version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"  # Change this line to use a different host port
    depends_on:
      - apache
  apache:
    image: httpd:latest
    ports:
      - "8082:80"
